"""Where every number in this project comes from.

Answers, from the files themselves rather than from a written claim: which
dataset trained which model, how many rows it had, and whether those rows
describe real people or a simulator.

This exists because the project's biggest research risk is not a wrong model —
it is a reader assuming a figure measured real behaviour when it did not. Row
counts are read from disk at request time, so this page cannot drift out of
date the way a hand-maintained table in a report does.
"""

from __future__ import annotations

import csv
import json
import logging
from dataclasses import asdict, dataclass
from functools import lru_cache
from pathlib import Path

from api import db

log = logging.getLogger("mos.provenance")

ROOT = Path(__file__).resolve().parents[2]


@dataclass
class Dataset:
    key: str
    name: str
    path: str
    nature: str          # real | simulated | synthetic | derived
    origin: str
    used_by: list[str]
    note: str = ""


#: Every dataset in the repository, whether or not a model consumes it.
#: Unused ones are listed deliberately — "we shipped data nothing reads" is
#: exactly the kind of thing a viva should surface, not something to hide.
DATASETS: list[Dataset] = [
    Dataset(
        key="kaggle_campaign",
        name="Digital Marketing Campaign dataset",
        path="modules/m1_segmentation/digital_marketing_campaign_dataset.csv",
        nature="synthetic",
        origin="Kaggle — generated by its publisher, not observed traffic",
        used_by=["M1 segmentation (research)", "M2 conversion model"],
        note="The 8,000-user set behind the segmentation study.",
    ),
    Dataset(
        key="bank_marketing",
        name="UCI Bank Marketing",
        path="data/raw/bank_marketing/bank-additional-full.csv",
        nature="real",
        origin="UCI ML Repository — a real Portuguese bank's campaigns",
        used_by=["M3 conversion / drop-off validation"],
        note="The only genuinely real behavioural dataset in the project. "
             "It is what makes the M3 validation number meaningful.",
    ),
    Dataset(
        key="m3_simulated_events",
        name="Module 3 simulated event log",
        path="modules/m3_analytics/data/simulated/event_logs.csv",
        nature="simulated",
        origin="modules/m3_analytics/src/simulator.py",
        used_by=["M3 attribution study", "M3 conversion / drop-off training"],
        note="Multi-platform journeys the real email campaign cannot supply.",
    ),
    Dataset(
        key="m3_features",
        name="Module 3 engineered features",
        path="modules/m3_analytics/data/processed/features.csv",
        nature="derived",
        origin="built from the simulated event log",
        used_by=["M3 conversion model", "M3 drop-off model"],
    ),
    Dataset(
        key="m2_events",
        name="Module 2 campaign event log",
        path="modules/m2_automation/outputs/event_logs.csv",
        nature="simulated",
        origin="modules/m2_automation/src/simulator.py",
        used_by=["M2 strategy comparison (research)"],
    ),
    Dataset(
        key="goal_tone_training",
        name="Goal / tone labelled corpus",
        path="data/processed/goal_tone_dataset_training.csv",
        nature="derived",
        origin="auto-labelled from marketing copy, then filtered",
        used_by=["M4 campaign-goal classifier", "M4 tone classifier"],
        note="Rebuilt with per-target confidence filtering: 114 rows became 527 "
             "(453 usable for goal, 173 for tone). The `needs_review` flag is "
             "deliberately not used as a filter — it is set on 575 of 689 rows, "
             "and cross-validation showed excluding them made both classifiers "
             "worse. Still small: quote cross-validated figures, not single "
             "splits. See scripts/tune_goal_tone_threshold.py.",
    ),
    Dataset(
        key="engagement",
        name="Engagement dataset",
        path="data/raw/datasets/your_engagement_dataset.csv",
        nature="synthetic",
        origin="a 6-column projection of 'Social Media Engagement Dataset.csv' "
               "— identical texts and identical like counts",
        used_by=["M4 engagement regressor"],
        note="Analysis found no relationship between post text and engagement: "
             "every text feature has |rho| < 0.013 with p > 0.16, and engagement "
             "does not differ by platform (Kruskal-Wallis p = 0.68). The "
             "engagement figures appear to have been generated independently of "
             "the text, which is why no model can learn from it.",
    ),
    Dataset(
        key="instagram",
        name="Instagram posts",
        path="data/raw/datasets/Instagram-datasets.csv",
        nature="real",
        origin="public platform export",
        used_by=[],
        note="Comment-level scrape: one row per *comment* with that comment's "
             "own likes. It pairs no post text with post engagement, so it "
             "cannot train the engagement model — an earlier assumption that "
             "it could was wrong.",
    ),
    Dataset(
        key="tiktok",
        name="TikTok posts",
        path="data/raw/datasets/TikTok-datasets.csv",
        nature="real",
        origin="public platform export",
        used_by=[],
        note="Comment-level scrape, same limitation as the Instagram file.",
    ),
    Dataset(
        key="facebook",
        name="Facebook posts",
        path="data/raw/datasets/Facebook-datasets.csv",
        nature="real",
        origin="public platform export",
        used_by=[],
        note="Comment-level scrape, same limitation as the Instagram file.",
    ),
]


MODELS = [
    {
        "key": "m1_hybrid",
        "name": "M1 hybrid segmentation",
        "kind": "rules + K-Means + hierarchical, combined by agreement",
        "trained_on": "kaggle_campaign",
        "headline": "conversion separation 38.4 points",
        "honest": "Silhouette 0.087 — the behavioural clusters overlap heavily. "
                  "The segments are commercially useful without being "
                  "geometrically clean, and both facts belong in the report.",
        "artifact": "modules/m1_segmentation/segment.py",
    },
    {
        "key": "m1_classifier",
        "name": "M1 inductive classifier",
        "kind": "RandomForest over behavioural features",
        "trained_on": "kaggle_campaign",
        "headline": "held-out accuracy 0.92",
        "honest": "The notebook version scored ~1.00 because the target was also "
                  "an input feature. This one sees behavioural features only, so "
                  "0.92 is a real generalisation number.",
        "artifact": "modules/m1_segmentation/segment.py",
    },
    {
        "key": "m3_conversion",
        "name": "M3 conversion model",
        "kind": "XGBoost",
        "trained_on": "m3_features",
        "headline": "AUC ≈ 0.98 on simulated data",
        "honest": "Trained and measured on the simulator. Applying it to a live "
                  "audience is a transfer across distributions: the ranking "
                  "holds, the probabilities are not calibrated for a new site.",
        "artifact": "outputs/models/conversion_xgboost.pkl",
    },
    {
        "key": "m3_dropoff",
        "name": "M3 drop-off model",
        "kind": "XGBoost",
        "trained_on": "m3_features",
        "headline": "AUC ≈ 0.99 on simulated data",
        "honest": "Same transfer caveat. On the live audience it produced no "
                  "visitor above the 60% risk threshold, which the analytics "
                  "service reports as a calibration warning rather than a zero.",
        "artifact": "outputs/models/drop_off_xgboost.pkl",
    },
    {
        "key": "m4_goal",
        "name": "M4 campaign-goal classifier",
        "kind": "TF-IDF + balanced logistic regression (beat Sentence-BERT + XGBoost)",
        "trained_on": "goal_tone_training",
        "headline": "accuracy 0.80 · macro-F1 0.54 on 453 rows",
        "honest": "Was trained on 114 rows because a row had to clear the "
                  "confidence bar for goal AND tone; the two classifiers train "
                  "separately, so that discarded good data. Filtering per target "
                  "gives 453 rows. Macro-F1 0.54 against accuracy 0.80 is the "
                  "number that matters: `awareness` is over half the corpus, so "
                  "accuracy flatters a model that handles the rare classes badly.",
        "artifact": "models/best_goal_model.pkl",
    },
    {
        "key": "m4_tone",
        "name": "M4 tone classifier",
        "kind": "TF-IDF + balanced logistic regression (beat Sentence-BERT + XGBoost)",
        "trained_on": "goal_tone_training",
        "headline": "accuracy 0.89 · macro-F1 0.72 on 173 rows",
        "honest": "Previously 0.91 accuracy on 114 rows — a higher number from a "
                  "smaller, easier test set. With 173 rows and more classes "
                  "present the score is slightly lower and considerably more "
                  "trustworthy. `humorous` has one example and cannot be learned "
                  "or evaluated.",
        "artifact": "models/best_tone_model.pkl",
    },
    {
        "key": "m4_engagement",
        "name": "M4 engagement regressor",
        "kind": "RandomForest / XGBoost over text-derived features",
        "trained_on": "engagement",
        "headline": "measured below — read it, do not assume it",
        "honest": "Previously reported R² 0.99. That came from leakage: likes, "
                  "comments, shares and impressions were left in the feature set "
                  "while the target was (likes+comments+shares)/impressions. With "
                  "the leak removed the model has no measurable skill, and no "
                  "text feature correlates with engagement in this dataset "
                  "(all p > 0.16). Its weight in the content score was reduced "
                  "from 0.45 to 0.20 as a result.",
        "artifact": "models/best_engagement_model.pkl",
        "metrics_file": "models/engagement_metrics.json",
    },
]


def _count_rows(path: Path) -> int | None:
    """Row count excluding the header, or None when the file is absent."""
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8", errors="ignore", newline="") as fh:
            return max(0, sum(1 for _ in csv.reader(fh)) - 1)
    except OSError as exc:                              # pragma: no cover
        log.warning("could not count %s: %s", path, exc)
        return None


@lru_cache(maxsize=1)
def _dataset_rows() -> dict[str, int | None]:
    return {d.key: _count_rows(ROOT / d.path) for d in DATASETS}


def datasets() -> list[dict]:
    counts = _dataset_rows()
    out = []
    for d in DATASETS:
        rows = counts.get(d.key)
        out.append({
            **asdict(d),
            "rows": rows,
            "present": rows is not None,
            "unused": not d.used_by,
        })
    return out


def _measured(entry: dict) -> dict | None:
    """Metrics written by the trainer, if it recorded any.

    Preferred over the prose in MODELS: a number produced by the last training
    run cannot be stale in the way a hand-written claim can.
    """
    rel = entry.get("metrics_file")
    if not rel:
        return None
    path = ROOT / rel
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):             # pragma: no cover
        return None


def models() -> list[dict]:
    by_key = {d.key: d for d in DATASETS}
    counts = _dataset_rows()
    out = []
    for m in MODELS:
        source = by_key.get(m["trained_on"])
        artifact = ROOT / m["artifact"]
        measured = _measured(m)

        entry = {
            **m,
            "dataset_name": source.name if source else m["trained_on"],
            "dataset_nature": source.nature if source else "unknown",
            "dataset_rows": counts.get(m["trained_on"]),
            "artifact_present": artifact.exists(),
            "measured": measured,
        }
        # Where the trainer recorded real numbers, they replace the prose.
        if measured:
            entry["headline"] = (
                f"R² {measured['r2']:+.2f} · Spearman {measured['spearman']:+.2f}"
                f" · baseline R² {measured['baseline_r2']:+.2f}"
            )
            entry["verdict"] = measured.get("verdict")
        out.append(entry)
    return out


def live_data_basis() -> dict:
    """How much of what the dashboard currently shows is real."""
    try:
        visitors = db.fetch_one(
            """SELECT count(*) AS total,
                      count(*) FILTER (WHERE is_synthetic)     AS synthetic,
                      count(*) FILTER (WHERE NOT is_synthetic) AS real
               FROM visitors""") or {}
        interactions = db.fetch_one(
            """SELECT count(*) AS total,
                      count(*) FILTER (WHERE is_real)     AS real,
                      count(*) FILTER (WHERE NOT is_real) AS simulated
               FROM interactions""") or {}
    except Exception as exc:                            # pragma: no cover
        return {"error": str(exc)[:200]}

    total = interactions.get("total") or 0
    real = interactions.get("real") or 0
    return {
        "visitors": visitors,
        "interactions": interactions,
        "real_share": round(real / total, 3) if total else None,
        "note": (
            "Simulated visitors flow through the same endpoints as real ones, so "
            "the distinction is stored per row (visitors.is_synthetic, "
            "interactions.is_real) rather than inferred. Every figure in the "
            "dashboard carries the resulting basis label."
        ),
    }


def goal_tone_metrics() -> dict | None:
    """The measured goal/tone numbers, straight from the training artifact."""
    path = ROOT / "models" / "goal_tone_training_metrics.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):             # pragma: no cover
        return None

    return {
        "dataset_rows": data.get("dataset_rows"),
        "selection": data.get("selection", {}),
        "results": [
            {
                "target": r.get("target"),
                "model": r.get("model"),
                "accuracy": r.get("accuracy"),
                "weighted_f1": r.get("weighted_f1"),
                "macro_f1": r.get("macro_f1"),
            }
            for r in data.get("results", [])
        ],
    }


def report() -> dict:
    ds = datasets()
    return {
        "datasets": ds,
        "models": models(),
        "goal_tone_metrics": goal_tone_metrics(),
        "live": live_data_basis(),
        "summary": {
            "n_datasets": len(ds),
            "n_present": sum(1 for d in ds if d["present"]),
            "n_unused": sum(1 for d in ds if d["unused"]),
            "real_datasets": sum(1 for d in ds if d["nature"] == "real"),
            "simulated_or_synthetic": sum(
                1 for d in ds if d["nature"] in ("simulated", "synthetic")),
        },
    }
